# Prometheus config
scrape_configs:

  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['callisto:9091']

  - job_name: 'hdfs-tdh'
    scrape_interval: 180m # Depends on how often the name node writes a fsimage file.
    scrape_timeout:  200s # Depends on size
    static_configs:
    - targets: ['callisto:9010']

    #metrics_path: /ws/v1/cluster/metrics
  - job_name: 'yarn-tdh'
    static_configs:
    - targets: ['callisto:9113']

  - job_name: 'yarnapps-tdh'
    static_configs:
    - targets: ['callisto:9114']

  - job_name: 'spark-tdh'
    static_configs:
    - targets: ['callisto:9108']

  - job_name: 'mysql-tdh'
    scrape_interval: 300s
    static_configs:
    - targets: ['callisto:9104']